# **This is a program which can convert a matrix into Echelon Form **
### ***BY -Anuj Singh Negi, 19BAI10021***

In [1]:
import numpy as np
from fractions import Fraction as Fc
from sympy import * 
import math

**Condition to check whether Matrix can be converted to Echelon form or not**

In [2]:
def ConditionBasic(A):
  ret = 0
  for i in range(row):
    if(A[i][0]!=0):
      continue
    
    else:
      ret +=1
  
  return ret

### **To convert all values to float**

In [3]:
def ConvertFloat(A):
  A = map(round, A)

**To Replace or Interchange the Rows**

In [4]:
def ReplaceRows(A, take, rep):
  
  for j in range(column):
      A[take][j], A[rep][j] = A[rep][j], A[take][j]

**To Update the values using Elimination Method**

In [5]:
def Update(A, take, up, ele):
  m = float(A[take][ele])
  n = float(A[up][ele])

  D= m/n

  for j in range(column):
    A[take][j] = float(A[take][j]) - (float(A[up][j])*D)
    #loooook Here


**A function to find Greatest Common Divisor**

In [6]:
def gcd(a,b) : 
    if (a < b) : 
        return gcd(b, a) 
      
    # base case 
    if (abs(b) < 0.001) : 
        return a 
    else : 
        return (gcd(b, a - math.floor(a / b) * b))

**This Function divides a row if a common divisor or HCF exists**

In [7]:
def ConditionAdv(A, r):

  #Conditions to divide a row if a HCF exists
  L=[]

  for j in range(column):
    if A[r][j] >0 or A[r][j]<0:
      L.append(A[r][j]) 

  L =  [abs(ele) for ele in L]
  L.sort()

  L1=[]
  for i in range(len(L)):
    L1.append(gcd(L[i], L[0]))

  divisor=L1[len(L1)-1]
  for i in range(1, len(L1)):
    if(L1[i] != divisor):
      divisor =1
      break
    else:
      continue
      
  #print("**** ", divisor)
  
  divisor = float(divisor)

  for j in range(column):
    A[r][j] = float(A[r][j])/divisor
  
    #print("&& ", A[r])

  #Condition to convert element if all are negative
  L3=[]

  for j in range(column):
    if A[r][j] >0 or A[r][j]<0:
      L3.append(A[r][j]) 
  
  multiplier = -1
  for i in L3:
    if i > 0:
      multiplier = 1

  for j in range(column):
    if(A[r][j]!=0):
      A[r][j] = A[r][j]*multiplier

### **Convert Pivot values to 1**

In [8]:
def ConditionOne(A):
  for i in range(row):
    L=[]

    for j in range(column):
      if(A[i][j]!=0):
        L.append(A[i][j])

    if len(L) is 0:
      L.append(1) 

    for j in range(column):
      A[i][j] = float(A[i][j])/L[0]
      A[i][j] = round(A[i][j], 3)
      F = A[i][j].as_integer_ratio()
      if F[1] is 1:
        print(A[i][j], end="  ")
      else:
        print(F[0],"/", F[1], end = "   ")
      
      
    print()

# **Main Process to Convert into Row Echelon Form**

In [9]:
def Process(A):

  i=1
  while(A[0][0]==0):
    ReplaceRows(A, 0, i)
    i+=1
    #print("Zero found in first row - replacing row 0 with %d - " %i)
    #print(A)
  
  for steps in range(1, row):
    for i in range(row):
      ConditionAdv(A, i)

    for r in range(steps, row):
      if A[r][steps-1] is 0:
        continue
      
      else:
        Update(A, r, steps-1, steps-1)

# **A function to call other functions**

In [10]:
def Echelon(A, row, column):

  ConvertFloat(A)
  print("Matrix = \n", A)
  s= ConditionBasic(A)
  
  if(s == row):
    print("Echelon Form for this Matrix doesn't exist")

  else:
    print("Echelon Form for this Matrix exist")
    Process(A)
    print("___________________________________________________________")
    print("Echelon Form - ")

    ConditionOne(A)

# **MAIN** **Function**

In [11]:
#To Enter the rows and columns

print('Enter the order (row X column) for the matrix: ')
row = int(input("Row: "))
column = int(input("Column: "))

Enter the order (row X column) for the matrix: 
Row: 3
Column: 3


**Here, the matrix is defined using direct values but can be edited as per user's choice.**

In [14]:
A = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='float64')
#A = [[4, 6, 9], [22, 5, 36], [1, 9, 15]]
Echelon(A, row, column)

Matrix = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Echelon Form for this Matrix exist
___________________________________________________________
Echelon Form - 
1.0  2.0  3.0  
0.0  1.0  2.0  
0.0  0.0  0.0  


## ***If User want to give the Matrix value one by one - ***

In [15]:
print('Enter the matrix: ')
for i in range(row):
  for j in range(column):
    A[i][j] = float(input("a%d%d - " %(i+1,j+1)))

Echelon(A, row, column)

Enter the matrix: 
a11 - 1
a12 - 2
a13 - 3
a21 - 4
a22 - 5
a23 - 6
a31 - 7
a32 - 8
a33 - 9
Matrix = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Echelon Form for this Matrix exist
___________________________________________________________
Echelon Form - 
1.0  2.0  3.0  
0.0  1.0  2.0  
0.0  0.0  0.0  


***This is a direct method using Sympy module, which can directly give Echelon form. (Being Used to verify the answer)***

In [16]:
from sympy import * 
  
M = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print("Matrix : {} ".format(M)) 
   
# Use sympy.rref() method  
M_rref = M.rref()   
      
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))   


Matrix : Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1))
